### ISSUE TITLE
css() function doesn't work with JSON

### ISSUE THREAD

**Issue by RongBranovate** [jstools/jqlite#13]
HI,
I'm trying to add css through the js with the .css() function and i have alot of css code to use, only thing is that the format where you could write:
```javascript
$('.myClass').css({"background-color":"yellow","font-weight": "bolder"});
```
doesn't work... i insted have to do it like this:

```javascript
$('.myClass').css("background-color","yellow");
$('.myClass').css("font-weight", "bolder");
```
which take alot of code and time, what can i do?

Thanks in advance

**Comment by RongBranovate** [comment]
As soon as i pressed the "send issue" button you implamented that :+1: 

Thanks!

**Comment by jgermade** [comment]
hehe! thanks you!
