### ISSUE TITLE
hasClass always returns true

### ISSUE THREAD

**Issue by AleCaste** [jstools/jqlite#14]
Hello,
I am having problems with the .hasClass method.
If a node elem has a class attribute defined, then it will no matter what the contents of that class attribute are, the method hasClass will always return true no matter which class name you pass it to. 
I don't know if someone else is experiencing the same problem.
I am using the latest version of this lib.

**Comment by AleCaste** [comment]
After having a look at jqlite.js I believe the code that says (lines 661-663):

```
          if( this[i].classList.item(className) ) {
              return true;
          }
```
Should be replaced with something like:
```
        for( var i2 = 0, len2 = this[i].classList.length; i2 < len2 ; i2++ ) {
          if(this[i].classList.item(i2)==className) {
              return true;
          }
        }
```
Or am I wrong?

**Comment by jgermade** [comment]
Fixed in commit [105f8de](https://github.com/jstools/jqlite/commit/105f8dec842224e70761fedfc623810f26d2ebc2)  (new release v0.2.5)

thanks @AleCaste !!

**Comment by AleCaste** [comment]
You're welcome.
I can see you've used the method 'contains' in the fix, but I'm not quite sure if that would work on the client side on all browsers. Would the array method 'indexOf' be a better alternative in this case?

**Comment by jgermade** [comment]
Hi @AleCaste this implementation is for browsers that support classList, old browsers will use the alternative definition of hasClass [see code](https://github.com/jstools/jqlite/blob/master/jqlite.js#L666).

**Comment by AleCaste** [comment]
Ahhh ok. I missed that. Thanks a lot for the clarification.

**Comment by jgermade** [comment]
ur welcome! thanks you for your feedback!
