### ISSUE TITLE
adding the .hover() function

### ISSUE THREAD

**Issue by RongBranovate** [jstools/jqlite#15]
Hi, 
would be awesome to have the .hover() function just like in jquery

thanks in advance

**Comment by jgermade** [comment]
Hi @RongBranovate ,

.appendTo(), .mouseenter(), .mouseleave() and .hover() has been added in release [v0.2.6](https://github.com/jstools/jqlite/releases/tag/v0.2.6)

Thanks again for your feedback!!

**Comment by RongBranovate** [comment]
awesome, thanks!

**Comment by jgermade** [comment]
ur welcome!!
