### ISSUE TITLE
why is the .off() function isn't working for me?

### ISSUE THREAD

**Issue by RongBranovate** [jstools/jqlite#16]
Hi @jgermade ,
i have this code where i want to be able to drag a button on the X axis and for some reason when i try to off() the 'mousemove' event on the 'mouseup' event it wont work, any i idea why?

Here is my code:
```javascript
  $(progress-button).on('mousedown', function(e){
        $(this).on("mousemove",function(e){
            $(this).css('left', e.pageX + 'px');
        });
    }).on('mouseup', function(){
      $(this).off('mousemove');
  });
```

**Comment by jgermade** [comment]
Hi @RongBranovate ,

in order to detach a listener from an element, handler needs to be passed, this should work:

``` js
function mousemove (e) {
    $(this).css('left', e.pageX + 'px');
}
 $(progress-button).on('mousedown', function(e){
      $(this).on("mousemove", mousemove);
    }).on('mouseup', function(){
      $(this).off('mousemove', mousemove);
    });

**Comment by RongBranovate** [comment]
Hi @jgermade , thanks for your reply,

The thing is i can't get the 'mouseup' to fire, the button just keeps moving even after i stoped pressing the mouse button down, its just moves to the right when i try to get to it....

**Comment by jgermade** [comment]
Hi @RongBranovate, I've found this: http://stackoverflow.com/questions/4065992/jquery-detecting-pressed-mouse-button-during-mousemove-event

**Comment by RongBranovate** [comment]
Hi @jgermade ,

I'll look into this, and let you know,
thanks!
