### ISSUE TITLE
adding the .offset() and the .position() functions

### ISSUE THREAD

**Issue by RongBranovate** [jstools/jqlite#17]
Hi @jgermade ,

is it possible to add the adding the .offset() and the .position() functions to jqlite?

Thanks in advance!

**Comment by jgermade** [comment]
Ok, looks good. I'll work on this soon

**Comment by RongBranovate** [comment]
awesome @jgermade !  
can't wait!

**Comment by jgermade** [comment]
Hi @RongBranovate , I'm still working on this, I want to ensure cross-browser compatibility

**Comment by RongBranovate** [comment]
Ok, awesome, let me know as soon as it's ready :+1:

**Comment by jgermade** [comment]
Hi @RongBranovate jqlite v0.2.7 includes offset and position functions!

thanks a lot for your feedback!!

**Comment by RongBranovate** [comment]
Thanks! awesome!
