### ISSUE TITLE
Implementing .getJSON()

### ISSUE THREAD

**Issue by RongBranovate** [jstools/jqlite#18]
Hi,
What would be the best way to implement the .getJSON() function from jQuery?

the jQuery docs say it's basicly a shorthand Ajax function, which is equivalent to:

```javascript
$.ajax({
  dataType: "json",
  url: url,
  data: data,
  success: success
});
```
would that work with ```jqlite``` ? is there anything that i should change?

Thanks in advance!

**Comment by jgermade** [comment]
Hi @RongBranovate jqlite aims to be a DOM handling library, you can find specific libraries for this stuff like [jengine-http](https://jstools.github.io/jengine/http/)

> with jengine-http

``` js
$http.get(url, data).then(function (response) {
   console.log('json received: ', response.data);
});
```

**Comment by RongBranovate** [comment]
Splendid! thanks!
