### ISSUE TITLE
add .hide() and .show() function

### ISSUE THREAD

**Issue by RongBranovate** [jstools/jqlite#21]
Hi, 
is it possible to add the .hide() and .show() functions to jqlite?

Thanks in advance.

**Comment by jgermade** [comment]
Hi @RongBranovate 

Working on this... do you think animations are needed? I usually use css animations only because of performance.

**Comment by RongBranovate** [comment]
Awesome! I'm using the .css() function for the animations (i can't use css
files) so no need for animation functions...

Thanks!
בתאריך 17 ביול' 2015 03:37,‏ "Jesús Germade" <notifications@github.com> כתב:

**Comment by RongBranovate** [comment]
Hi @jgermade,

Are those added?

**Comment by jgermade** [comment]
Hi @RongBranovate , I though that I did, but I didn't, whoops!

Now is included! [demo](http://plnkr.co/edit/dVRdCm9Z8lTnxwi5VexB?p=preview)

**Comment by RongBranovate** [comment]
Hi @jgermade thanks for the addition, one request: is it possible to add the speed functionality to ```hide()``` and ```show()```? 

For example:
```javascript
$('p').hide(1000);
//or 
$('p').show('fast');
```

**Comment by jgermade** [comment]
Hi @RongBranovate, hide/show now allows following parameters: .show/hide( duration [, easing ] [, complete ] )

'slow': 600ms
'normal': 400ms
'fast': 200ms
