### ISSUE TITLE
add the .add() function

### ISSUE THREAD

**Issue by RongBranovate** [jstools/jqlite#22]
Hi @jgermade ,

I'm trying to use the same event handler for multiple jquery objects and from what i've found jquery uses the .add() function like so:

```javascript
$(obj1).add(obj2).on('click', some_function);
```
is there another way to do so in jqlite? or is it possible to add the .add() function?

note: i'm not talking about css selectors like ```'.class1' ``` 

thanks in advance!

**Comment by jgermade** [comment]
Hi @RongBranovate, I think is a great idea... working on this!

**Comment by jgermade** [comment]
Hi @RongBranovate ,

.add() is added!

think is an usefull method, thanks as always!!

**Comment by RongBranovate** [comment]
awesome! thanks!
