### ISSUE TITLE
adding CSS functionality

### ISSUE THREAD

**Issue by RongBranovate** [jstools/jqlite#23]
Hi @jgermade , 

I'm trying to use the .css() function as the jquery docs describe here: http://api.jquery.com/css/
as follows:

```javascript
<script>
$( "#box" ).one( "click", function() {
  $( this ).css( "width", "+=200" );
});
</script>
```

What i'm basically trying to achieve is to change the ```background-position``` of a button so i'm going like this:
```javascript
  $('.Btn').hover(function(){
    $(this).css('backgroundPosition', '-=49');
  },function(){
    $(this).css('backgroundPosition', '+=49');
  });
```

but it's not working, is this option available and i'm making a mistake? or do you need to add it?

Thanks in advance!

**Comment by jgermade** [comment]
Hi @RongBranovate, this feature needs to be added. Just a little tweak in definition I guess

**Comment by jgermade** [comment]
Hi @RongBranovate, this featured has been added. Needs some unit tests but is tested in browser with the expected behavior.

Thanks as always!!

**Comment by RongBranovate** [comment]
Awesome! thanks!
