### ISSUE TITLE
add .prev() , .prevAll() , .siblings() functions

### ISSUE THREAD

**Issue by RongBranovate** [jstools/jqlite#24]
Hi, 
is it possible to add the ..prev() , .prevAll() , .siblings() functions to jqlite?

Will help a lot with DOM manipulation...

Thanks in advance.

**Comment by jgermade** [comment]
sure, seems to be useful same level selectors!

thanks @RongBranovate !!

**Comment by RongBranovate** [comment]
Awesome! I personally would love to get .prevAll() first if that's possible ;)

**Comment by jgermade** [comment]
Hi @RongBranovate, this features has been added.
Also needs some unit tests but are tested in browser with the expected behavior.

Thanks as always!!

**Comment by RongBranovate** [comment]
Awesome! thanks!
