### ISSUE TITLE
binding and unbinding keypress

### ISSUE THREAD

**Issue by RongBranovate** [jstools/jqlite#25]
Hi,

I'm trying to bind a function to when a user presses ESC on his keyboard and then unbind it right after he pressed.

How should i bind when using jqlite? i see that the .on() function dosn't support namespaces but there is no bind/unbind of .keypress() functions.... any other way?

Thanks in advance!

**Comment by jgermade** [comment]
maybe you can use .one(), adds a listener that is automatically detached once it runs

In any case, I'm going to review .on() in order to include namespaces

Thanks @RongBranovate !!

**Comment by jgermade** [comment]
I am working on enhance event bindings with namespaces. Meanwhile, I was thinking in your issue, maybe following code works for you:
``` js
function onEsc (e) {
   if( e.keyCode === 27 ) {
      console.log('ESC pressed');
      $(document.body).off('keydown', onEsc);
   }
}

$(document.body).on('keydown', onEsc);
```

**Comment by RongBranovate** [comment]
Thanks for the tip, the only problem is that i'm working with the media
API, and when i'm with a full screen video i can't seem to detect the ESC
key...
בתאריך 5 באוג' 2015 23:32,‏ "Jesús Germade" <notifications@github.com> כתב:

> I am working on enhance event bindings with namespaces. Meanwhile, I was
> thinking in your issue, maybe following code works for you:
>
> function onEsc (e) {
>    if( e.keyCode === 27 ) {
>       console.log('ESC pressed');
>       $(document.body).off('keydown', onEsc);
>    }
> }
>
> $(document.body).on('keydown', onEsc);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jstools/jqlite/issues/25#issuecomment-128139491>.
>

--

**Comment by jgermade** [comment]
html5 video?

**Comment by RongBranovate** [comment]
Yeah
בתאריך 6 באוג' 2015 01:31,‏ "Jesús Germade" <notifications@github.com> כתב:

> html5 video?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jstools/jqlite/issues/25#issuecomment-128170907>.
>

--

**Comment by jgermade** [comment]
unfortunatelly seems that fullscreen mode doesn't allow capture keyboard events

I was playing with this code to toggle fullScreen:
``` js
HTMLElement.prototype.requestFullscreen = HTMLElement.prototype.requestFullscreen || HTMLElement.prototype.mozRequestFullscreen || HTMLElement.prototype.webkitRequestFullscreen || HTMLElement.prototype.msRequestFullscreen;
$.fn.fullScreen = function () {
   this.each(function (index) {
      this.requestFullscreen();
   });
};
var isFullscreen = false;
$(document.body).on('keyup', function (e) {
   console.log('keyup', e.keyCode);
   if( e.keyCode === 27 ) {
      if( !isFullscreen ) {
         $('video').fullScreen();
      }
      isFullscreen = !isFullscreen;
   }
});
$(document.body).on('keydown', function (e) {
   console.log('keydown', e.keyCode);
});
```

**Comment by RongBranovate** [comment]
that's what i kinda did.... so you're saying my only option is to try to detect the video element size?

**Comment by jgermade** [comment]
really, not sure whick is the goal of the feature you're developing

**Comment by RongBranovate** [comment]
yeah, it's getting out of this issue's scope, thanks any way!
