### ISSUE TITLE
one() on multiple elements only unbind the activated element

### ISSUE THREAD

**Issue by RongBranovate** [jstools/jqlite#26]
I'm trying to remove an event handler given with ```one()```  to 2 different elements, i'm basically trying to get both elements to unbind when either one of them gets called:

my code looks like this:

```javascript
$('.elem1 , .elem2').one('click' ,function(){
// some code...
});
```
but when ```elem1``` is clicked and gets unbind, ```elem2``` does not, and clicking ```elem2``` will fire the event. Same goes if i click ```elem2``` first.

p.s. i don't want to remove all the previous ```click``` events from them, just this event.
any idea what would be the best solution here?

**Comment by RongBranovate** [comment]
I also tried to use an event handler as so:
```javascript
function foo(){
  var buttons = $(document.body).find('.elem1 , elem2');

  var myEventHandler = function(){
    //some code...
    buttons.off('click', myEventHandler);
  }

  buttons.on('click', myEventHandler);
}
```
but with no avail, the result was the same as i got with the ```one()``` function where only the pressed button got the event removed from it

**Comment by jgermade** [comment]
Hi @RongBranovate, this is a hard question.

In the case of .once()/.one() .off() is not working for now. This is because I need to embed handler into a function autoDetach(handler) wrapper. So the handler is not the function that is attached.

Finally I've created a onceListeners collector and is passing tests for release: [v0.2.11](/jstools/jqlite/releases/tag/v0.2.11)

please tell me if is working for you. And thanks, as always!!

**Comment by RongBranovate** [comment]
Hi @jgermade, this is still an issue.

I am using the first method i describered and from what i'm seeing, in ```jqlite.js``` lines 1242-1245:
```javascript
  var index = onceListeners.indexOf(listenerData);
          if( index >= 0 ) {
            onceListeners.splice(index, 1);
          }
```
if i have 2 elements with that event it only removes one of them(the one that got pressed), the other one is still assigned and will fire when pressed.

**Comment by jgermade** [comment]
Hi @RongBranovate , I think this is the expected behavior (like jquery).

Maybe this snippet can help you:

[demo in plunker](http://plnkr.co/edit/SAjtVOC4A7wPmMlfaloR?p=preview)

``` html
<div>
      <button class="once">Button 1</button>
    </div>
    <div>
      <button class="once">Button 2</button>
    </div>
    <div>
      <button class="once">Button 3</button>
    </div>
    <div>
      <button class="once">Button 4</button>
    </div>
    
    <br/>
    
    <div>
      <button class="reset">Reset</button>
    </div>
```

``` js
$(function () {
  
  var jButtons = $('button.once');
  
  function clickOnce (e) {
    alert('clicked ' + e.target.textContent);
    jButtons.off('click', clickOnce);
  }
  
  jButtons.one('click', clickOnce);
  
  $('button.reset').click(function () {
    jButtons.off('click', clickOnce);
    jButtons.one('click', clickOnce);
  });
  
});
```

**Comment by RongBranovate** [comment]
Hi @jgermade 

YES! This worked! thanks alot!

**Comment by jgermade** [comment]
thanks you @RongBranovate !!
