### ISSUE TITLE
Data API should be stored object

### ISSUE THREAD

**Issue by hoangnguyencong** [jstools/jqlite#28]
Code:

$('.myNode').data('myData', {myPro: 'my value'});
console.log($('.myNode').data());

output:
  DOMStringMap {myData: "[object Object]"}

expect:
 Object {myData: Object}

**Comment by jgermade** [comment]
Hi @hoangnguyencong , I've changed implementation to run as expected (like jquery does)

Also added $.fn.dataset to keep managing data-* (html5 handling) properties

Thanks for the feedback!

**Comment by jgermade** [comment]
Also, dataset works as fallback for data like jquery:
https://api.jquery.com/data/#data-html5

**Comment by hoangnguyencong** [comment]
Hi @jgermade, thank you so much.
