### ISSUE TITLE
Style change event detection

### ISSUE THREAD

**Issue by RongBranovate** [jstools/jqlite#29]
Hi @jgermade.

I have an element with a width in %, i'm trying to get a listener on that element that would fire when it gets re-sized.

I thought about using [MutationObserver](https://developer.mozilla.org/en/docs/Web/API/MutationObserver) but i need to keep it IE9 supported.

I saw [this](http://stackoverflow.com/questions/2157963/is-it-possible-to-listen-to-a-style-change-event) question, and what he answered in the question.
I was wandering, won't it screw-up the css function all togather?

This is what he wrote:
```javascript
(function() {
    var ev = new $.Event('style'),
        orig = $.fn.css;
    $.fn.css = function() {
        $(this).trigger(ev);
        return orig.apply(this, arguments);
    }
})();
```
*This will temporary override the internal prototype.css method and the redefine it with a trigger at the end.*

But i'm not sure that's what i need.... any idea?

**Comment by jgermade** [comment]
Hi @RongBranovate , I understand that what you need is detect when an element is resized in px. So when window is resized hence element may be already resized but width property value does not change.

You may watch window resize, and check element size change. Maybe this can help you: http://plnkr.co/edit/s4Qul9ydoAbqyBpX0hAH?p=preview
