### ISSUE TITLE
Adding WrapAll() and unWrap() function

### ISSUE THREAD

**Issue by Fire-Brand** [jstools/jqlite#33]
Is it possible to please add the ```WrapAll()``` and ```unWrap()``` function just like in jQuery?

Thanks in advance

**Comment by jgermade** [comment]
OK, I'll start working on this.

Thanks @Fire-Brand for your contribution!!

**Comment by jgermade** [comment]
Hi @Fire-Brand, sorry for the delay!

This functions are finally added in [v0.2.33](https://github.com/jstools/jqlite/releases/tag/v0.2.33)

Thanks for your feedback!! (as always)
