### ISSUE TITLE
Unbind all listeners of the same event type

### ISSUE THREAD

**Issue by Fire-Brand** [jstools/jqlite#34]
Hi @jgermade,

i'm having some issues with a 3rd party code overriding the HTML5 Media API ``` 'ended' ``` event and i want to remove all listeners from that element, then, either restore them to default or add my own with the ```.on()``` function.

I've seen that with jQuery i could have used ```video.unbind('ended')```.
Do you think it is possible to add this to jqlite? or can you think of an alternative ?

**Comment by jgermade** [comment]
Hi @Fire-Brand, you can use .off(eventName, handler)

both eventName, handler arguments and required for now

I think I'm going to add support for when handler missing, all handlers will be removed.

The issues queue is growing, I'll try to resolve all of the soon :smile: 

Thanks for the feedback!!

**Comment by Fire-Brand** [comment]
Awesome! That's good news, this is by far the most urgent issue in my book,
so i would love to see that eventName only functionality.

Thanks!

**Comment by Fire-Brand** [comment]
@jgermade , let me know if there anything i can do to help speed this up :v:

**Comment by jgermade** [comment]
Hi @Fire-Brand thanks a lot for your help!

issue is close to be done in PR #35 , just want to add some more tests

**Comment by Fire-Brand** [comment]
HI @jgermade, this is awesome! can't wait!

**Comment by jgermade** [comment]
Ok! merged!
is included in new version [v0.2.26](https://github.com/jstools/jqlite/releases/tag/v0.2.26)
as well as .noConflict() method

**Comment by Fire-Brand** [comment]
WooHoo!  :smiley:

**Comment by Fire-Brand** [comment]
Guess it's time to update the Readme file :hankey:

**Comment by jgermade** [comment]
for sure!! it's a little bit outdated :smile:

**Comment by jgermade** [comment]
Hi @Fire-Brand, finally starting to work on a better documentation :smile:
https://github.com/jstools/jqlite/tree/better-documentation
