### ISSUE TITLE
classListMethods never declared

### ISSUE THREAD

**Issue by john92ptr** [jstools/jqlite#43]
Возможно ошибка в строке 810
`if( !classListMethods.has(el, className) ) {
          el.className += ' ' + className;
        }`

classListMethods - нигде не объявлена

**Comment by jgermade** [comment]
Hey @john92ptr, thanks for the feedback!!

it has being fixed in release [v0.2.40](https://github.com/jstools/jqlite/releases/tag/v0.2.40)
