### ISSUE TITLE
jquery Plug-in throws and error

### ISSUE THREAD

**Issue by RongBranovate** [jstools/jqlite#9]
Hi,
I'm trying to add this jquery-injectCSS:  https://github.com/kajic/jquery-injectCSS

but when i load them in my js file i get:

Uncaught ReferenceError: jQuery is not defined

is there any way around this?

thanks in advance!

**Comment by jgermade** [comment]
Hi @RongBranovate, this is because library name is not jQuery.

You may solve this just by adding the this line before jquery-injectcss:
``` js
<script type="text/javascript">window.jQuery = jqlite;</script>
```

Thanks for your feedback!

**Comment by RongBranovate** [comment]
thanks! solved it!

**Comment by RongBranovate** [comment]
Wait, now that i'm using the plugin im getting : 

Uncaught TypeError: jQuery.extend is not a function

**Comment by jgermade** [comment]
It's normal

$.extend is not provided by jqlite, jqlite is focused in DOM handling.

extend feature is provided by [jstools/utils](https://github.com/jstools/utils)

To solve this problem there are some solutions, just need to implement extend method, for example:

adding your own method:
``` html
<script type="text/javascript">
$.extend = function () {
    var dest = [].shift.call(arguments),
      src = [].shift.call(arguments),
      key;

  while( src ) {
    for( key in src) {
      dest[key] = src[key];
    }
    src = [].shift.call(arguments);
  }

  return dest;
}
</script>
```

or maybe extending $ with all jstools/utils methods:
``` html
<script type="text/javascript" src="vendor/jstools/utils.js"></script>
<script type="text/javascript"> $utils.extend($, $utils); </script>
```

if you are using lodash or underscore, you can do:
``` html
<script type="text/javascript"> $.extend = _.extend; </script>
```

**Comment by RongBranovate** [comment]
Hi @jgermade !
thanks for the reply,
i've used your function here, now getting : 
Uncaught TypeError: jQuery(...).appendTo is not a function

**Comment by jgermade** [comment]
hi again @RongBranovate, .appendTo() is also included to jqlite

thanks again!!
